#!/bin/sh

uci delete nginx._redirect2ssl.return
uci add_list nginx._redirect2ssl.include='restrict_locally'
uci add_list nginx._redirect2ssl.include='conf.d/*.locations'
uci commit
/etc/init.d/nginx reload
