#!/bin/sh

cat >/etc/hotplug.d/dhcp/20-det-clients <<EOF
#!/bin/sh
[ ! -e '/etc/clients' ] && touch /etc/clients
[ "\$ACTION" = "update" -o "\$ACTION" = "add" ] && {
    if [ "\$(awk '\$1<20 {print 0}' /proc/uptime)" == "0" ]; then
        flock -x /tmp/det-clients.lock -c "lua /usr/share/hiui/rpc/device.lua \$MACADDR \$IPADDR \$HOSTNAME Wired"
    else
        local online=\$(awk '\$4==\$MACADDR {print \$3}' /proc/net/arp)
        flock -x /tmp/det-clients.lock -c "lua /usr/share/hiui/rpc/device.lua \$MACADDR \$IPADDR \$HOSTNAME \$online"
    fi
}
EOF

[ -d /etc/hotplug.d/firewall ] || mkdir /etc/hotplug.d/firewall
cat >/etc/hotplug.d/firewall/80-add-block <<EOF
#!/bin/sh
[[ -e '/tmp/add-block.lock' && \$ACTION == 'add' ]] && exit 0

if [ \$ACTION == 'add' ]; then
    flock -xn /tmp/add-block.lock -c "block-and-qos.sh addBlockList"
fi
EOF

cat >/etc/hotplug.d/iface/99-wrtbwmon <<EOF
#!/bin/sh

[ "\$ACTION" = ifup -o "\$ACTION" = ifupdate ] || exit 0
[ "\$ACTION" = ifupdate -a -z "\$IFUPDATE_ADDRESSES" -a -z "\$IFUPDATE_DATA" ] && exit 0

/etc/init.d/wrtbwmon restart

logger -t wrtbwmon "Restart for \$ACTION of \$INTERFACE (\$DEVICE)"
EOF

chmod +x /etc/hotplug.d/dhcp/20-det-clients
chmod +x /etc/hotplug.d/firewall/80-add-block
chmod +x /etc/hotplug.d/iface/99-wrtbwmon
