#
# Copyright (C) 2022 Jianhui Zhao <zhaojh329@gmail.com>
#
# This is free software, licensed under the MIT.
#

include $(TOPDIR)/rules.mk

APP_TITLE:=Network
APP_NAME:=network

include ../../hiui.mk

# call BuildPackage - OpenWrt buildroot signature
